export interface Company {
  name: string
  source: "From Brief" | "AI Researched" | "Manually Added"
  justification: string
  isNew?: boolean
}

export interface ReasonedText {
  text: string
  reasoning: string
}

export interface DecodedBrief {
  brief: ReasonedText
  expertise: ReasonedText[]
  companies: {
    primary: Company[]
    secondary: Company[]
  }
  scoring: string
}

export interface ReasonedKeyword {
  text: string
  reasoning: string
}

export interface KeywordData {
  function: ReasonedKeyword[]
  knowledge: ReasonedKeyword[]
  seniority: ReasonedKeyword[]
}

export interface Expert {
  id: string
  name: string
  title: string
  company: string
  score: number
  reasoningSummary: string
  scoringBreakdown: {
    criteria: string
    weight: number
    score: number
    reason: string
  }[]
}

export type BenchmarkCategory = "relevant" | "ambiguous" | "irrelevant"




export interface JobTitleBenchmarkItem {
  id: string
  title: string
  company: string
  initialCategory: BenchmarkCategory
  currentCategory: BenchmarkCategory
  reasoning: string
}

export interface Stage {
  id: number
  title: string
  status: "queued" | "processing" | "completed"
  total: number
  processed: number
  summary: string
  feed: string[]
}

export interface DecodingProcess {
  id: string
  name: string
  reasoning: string
  status: "in-progress" | "completed" | "needs-review"
  step: number
  brief: DecodedBrief
  companies: {
    primary: Company[]
    secondary: Company[]
  }
  keywords: KeywordData
  benchmarkData: JobTitleBenchmarkItem[]
  benchmarkRound: number
  experts: Expert[]
  finalExpertCount: number
}

export const initialDecodedBrief: DecodedBrief = {
  brief: {
    text: "Seeking an expert in global shipping logistics, specifically with experience in pricing and cargo flow management for containerized goods. The ideal candidate should have a deep understanding of trade lanes between Asia and Europe.",
    reasoning:
      "This summary was generated by extracting the core objectives, required skills, and context from the original project brief provided by the user.",
  },
  expertise: [
    {
      text: "Global Shipping Logistics",
      reasoning: "Core domain identified directly from the brief's opening sentence.",
    },
    {
      text: "Containerized Goods",
      reasoning: "Specific type of cargo mentioned, crucial for filtering relevant experience.",
    },
    {
      text: "Pricing & Cargo Flow Management",
      reasoning: "Two key responsibilities explicitly requested in the project brief.",
    },
    {
      text: "Asia-Europe Trade Lanes",
      reasoning: "Geographic focus area specified as a requirement for the ideal candidate.",
    },
    {
      text: "Freight Forwarding",
      reasoning: "Inferred related field; experts often move between carriers and forwarders.",
    },
  ],
  companies: {
    primary: [
      {
        name: "Maersk",
        source: "From Brief",
        justification: "Explicitly mentioned as a key player in container shipping.",
      },
      {
        name: "MSC",
        source: "From Brief",
        justification: "A major competitor to Maersk, relevant to the brief's context.",
      },
      { name: "CMA CGM", source: "From Brief", justification: "Another top-tier global container shipping line." },
      {
        name: "Hapag-Lloyd",
        source: "From Brief",
        justification: "Significant presence in the Asia-Europe trade lanes.",
      },
    ],
    secondary: [
      {
        name: "Kuehne+Nagel",
        source: "From Brief",
        justification: "A leading global freight forwarder mentioned in the context.",
      },
      {
        name: "DSV",
        source: "From Brief",
        justification: "Another major player in global logistics and freight forwarding.",
      },
    ],
  },
  scoring:
    "1. Direct Relevance (0.4): Hands-on experience in Pricing & Cargo Flow.\n2. Sub-sector Experience (0.3): Worked at a primary target company.\n3. Viewpoint Node (0.15): Title contains 'Manager', 'Director', or 'Head'.\n4. Seniority (0.15): 10+ years of experience in the industry.",
}

export const initialKeywords: KeywordData = {
  function: [
    { text: "Logistics", reasoning: "Primary function derived from 'global shipping logistics'." },
    { text: "Pricing", reasoning: "A core required skill mentioned explicitly in the brief." },
    { text: "Cargo Flow", reasoning: "The second core skill required for the role." },
    { text: "Trade Manager", reasoning: "A common job title for experts managing specific trade lanes." },
    { text: "Freight", reasoning: "A broad but essential keyword covering the industry." },
  ],
  knowledge: [
    { text: "Asia-Europe Trade", reasoning: "The specific geographic expertise requested." },
    { text: "Container Shipping", reasoning: "Narrows the search to the correct sub-sector of logistics." },
    { text: "Supply Chain", reasoning: "A related, slightly broader field to catch relevant profiles." },
  ],
  seniority: [
    { text: "Senior", reasoning: "Targets experienced, non-junior roles." },
    { text: "Head of", reasoning: "Identifies leadership and high-level responsibility." },
    { text: "Director", reasoning: "A standard keyword for senior management positions." },
    { text: "VP", reasoning: "Captures executive-level candidates." },
    { text: "Manager", reasoning: "A baseline keyword for roles with responsibility." },
  ],
}

export const initialExperts: Expert[] = [
  {
    id: "1",
    name: "Annette Black",
    title: "Global Head of Ocean Freight",
    company: "Maersk",
    score: 4.8,
    reasoningSummary:
      "Excellent match. Direct experience at a primary target company with a highly relevant leadership title.",
    scoringBreakdown: [
      {
        criteria: "Direct Relevance",
        weight: 0.4,
        score: 5,
        reason: "Title 'Global Head of Ocean Freight' directly maps to requested expertise in shipping logistics.",
      },
      {
        criteria: "Sub-sector Experience",
        weight: 0.3,
        score: 5,
        reason: "Currently employed at Maersk, which was listed as a Primary Target company.",
      },
      {
        criteria: "Viewpoint Node",
        weight: 0.15,
        score: 5,
        reason: "Title contains 'Global Head', indicating high seniority and strategic oversight.",
      },
      {
        criteria: "Seniority",
        weight: 0.15,
        score: 4,
        reason: "Public profile indicates 15+ years of progressive experience in the maritime industry.",
      },
    ],
  },
  {
    id: "2",
    name: "Cameron Williamson",
    title: "Senior Trade Manager, APAC-EU",
    company: "CMA CGM",
    score: 4.6,
    reasoningSummary: "Strong candidate. Title explicitly mentions the key trade lane (APAC-EU) and a target company.",
    scoringBreakdown: [
      {
        criteria: "Direct Relevance",
        weight: 0.4,
        score: 5,
        reason:
          "Title 'Senior Trade Manager, APAC-EU' is a perfect match for the requested Asia-Europe trade lane expertise.",
      },
      {
        criteria: "Sub-sector Experience",
        weight: 0.3,
        score: 5,
        reason: "Works at CMA CGM, a Primary Target company.",
      },
      {
        criteria: "Viewpoint Node",
        weight: 0.15,
        score: 4,
        reason: "Title contains 'Senior Manager', which aligns with the desired experience level.",
      },
      {
        criteria: "Seniority",
        weight: 0.15,
        score: 3,
        reason: "Profile shows 8 years of focused experience in this role.",
      },
    ],
  },
]

export const initialBenchmarkData: JobTitleBenchmarkItem[] = [
  {
    id: "job-1",
    title: "Head of Trade Management, Asia-Europe",
    company: "Hapag-Lloyd",
    initialCategory: "relevant",
    currentCategory: "relevant",
    reasoning:
      "Contains 'Head', 'Trade Management', and the key 'Asia-Europe' phrase. Matches multiple high-value keywords.",
  },
  {
    id: "job-2",
    title: "Senior Pricing Manager - Ocean Freight",
    company: "Maersk",
    initialCategory: "relevant",
    currentCategory: "relevant",
    reasoning:
      "Contains 'Senior', 'Pricing Manager', and 'Ocean Freight'. Directly aligns with core skill requirements.",
  },
  {
    id: "job-4",
    title: "Logistics Coordinator",
    company: "A.P. Moller - Maersk",
    initialCategory: "ambiguous",
    currentCategory: "ambiguous",
    reasoning:
      "Contains 'Logistics' but 'Coordinator' title is often junior. Needs review to determine actual responsibilities.",
  },
  {
    id: "job-8",
    title: "Warehouse Manager",
    company: "Amazon",
    initialCategory: "irrelevant",
    currentCategory: "irrelevant",
    reasoning: "Focus on 'Warehouse' is land-based logistics, not ocean freight. Company is not a target.",
  },
  {
    id: "job-11",
    title: "Director of Global Logistics",
    company: "MSC",
    initialCategory: "relevant",
    currentCategory: "relevant",
    reasoning: "Contains 'Director' and 'Global Logistics'. Strong signal for relevance and seniority.",
  },
  {
    id: "job-12",
    title: "Freight Forwarding Agent",
    company: "Kuehne+Nagel",
    initialCategory: "ambiguous",
    currentCategory: "ambiguous",
    reasoning: "Contains 'Freight Forwarding' but 'Agent' can be a junior role. Ambiguous seniority.",
  },
]

export const secondBenchmarkData: JobTitleBenchmarkItem[] = [
  {
    id: "job-13",
    title: "VP of Cargo Flow",
    company: "CMA CGM",
    initialCategory: "relevant",
    currentCategory: "relevant",
    reasoning: "AI calibrated: 'VP' and 'Cargo Flow' are now considered highly relevant signals.",
  },
  {
    id: "job-14",
    title: "Trade Lane Analyst",
    company: "Maersk",
    initialCategory: "relevant",
    currentCategory: "relevant",
    reasoning: "AI calibrated: 'Trade Lane' is a strong keyword. 'Analyst' is now considered potentially relevant.",
  },
  {
    id: "job-15",
    title: "Logistics Operations Manager",
    company: "DSV",
    initialCategory: "ambiguous",
    currentCategory: "ambiguous",
    reasoning: "AI calibrated: 'Logistics Manager' is relevant, but 'Operations' is broad. Needs user clarification.",
  },
  {
    id: "job-16",
    title: "Customs Broker",
    company: "FedEx",
    initialCategory: "irrelevant",
    currentCategory: "irrelevant",
    reasoning: "AI calibrated: 'Customs' is related but not core to cargo flow/pricing. Company is not a target.",
  },
  {
    id: "job-17",
    title: "Intermodal Specialist",
    company: "MSC",
    initialCategory: "ambiguous",
    currentCategory: "ambiguous",
    reasoning: "'Intermodal' is relevant to container logistics, but the specific responsibilities are unclear.",
  },
]
